[package]
name = "blink1"
version = "0.1.3"
authors = ["Colin Edwards <colin@recursivepenguin.com>"]
edition = "2021"
repository = "https://github.com/DDRBoxman/blink1-rs"
description = "Library to control blink(1) devices"
license = "MIT"

[dependencies]
hidapi = "2.6.1"
